class ReportBrandingService {
  const ReportBrandingService();

  String get companyName =>
      'Arrow Fleet Manager';

  String get reportTitle =>
      'Fleet Report';

  String get footer =>
      'Generated by Arrow Fleet Manager';

  String get version =>
      'v0.8.5';
}