class ReportBrandingService {
  const ReportBrandingService();

  String get companyName =>
      'FleetIQ';

  String get reportTitle =>
      'Fleet Report';

  String get footer =>
      'Generated by FleetIQ';

  String get version =>
      'v0.8.5';
}
